update

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -63,58 +63,55 @@ jobs:
           -Dspring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false \
           -DskipTests
       
-       - name: Upload compiled JAR
-         uses: actions/upload-artifact@v2
-         with:
+      - name: Upload compiled JAR
+        uses: actions/upload-artifact@v2
+        with:
           name: compiled-backend
-         path: target/*.jar
-
-
-         
+          path: target/*.jar
 
   build-artifact:
     name: Build AMI
-      needs: compile-backend
-     runs-on: ubuntu-latest
-     outputs:
+    needs: compile-backend
+    runs-on: ubuntu-latest
+    outputs:
       version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
       ami_id: ${{ steps.ami.outputs.ami_id }}
-     if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
-     steps:
-     - name: Checkout Repository
+    if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
+    steps:
+      - name: Checkout Repository
         uses: actions/checkout@v4
       
-    - name: Configure AWS Credentials
-         uses: aws-actions/configure-aws-credentials@v4
-         with:
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: il-central-1
       
-    -name: Ensure backend-jar directory exists
+      - name: Ensure backend-jar directory exists
         run: mkdir -p ./backend-jar
 
-   - name: Download compiled JAR
+      - name: Download compiled JAR
         uses: actions/download-artifact@v2
-       with:
-       name: compiled-backend
-       path: ./backend-jar
+        with:
+          name: compiled-backend
+          path: ./backend-jar
 
-    - name: Check backend-jar content
-       run: |
-       echo "Current directory:"
-       pwd
-       echo "Contents of current directory:"
-       ls -la
-       echo "Contents of ./backend-jar:"
-       ls -la ./backend-jar
-       echo "JAR file details:"
-       find ./backend-jar -name "*.jar" -type f -exec ls -l {} \;
+      - name: Check backend-jar content
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Contents of current directory:"
+          ls -la
+          echo "Contents of ./backend-jar:"
+          ls -la ./backend-jar
+          echo "JAR file details:"
+          find ./backend-jar -name "*.jar" -type f -exec ls -l {} \;
       
-    - name: Packer Init
+      - name: Packer Init
         run: packer init .
 
-     - name: Get latest AMI from Launch Template
+      - name: Get latest AMI from Launch Template
         run: |
           LATEST_LT_VERSION=$(aws ec2 describe-launch-template-versions \
             --launch-template-name "${{ env.LAUNCH_TEMPLATE_NAME }}" \
@@ -130,18 +127,18 @@ jobs:
       
       - name: Packer Build
         run: |
-       JAR_FILE=$(find ./backend-jar -name "*.jar" -type f)
-       if [ -z "$JAR_FILE" ]; then
-        echo "Error: No JAR file found"
-        exit 1
-       fi
-       echo "Using JAR file: $JAR_FILE"
-       packer build \
-        -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
-        -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
-        -var "COMPILED_JAR_PATH=$JAR_FILE" \
-        -var "source_ami=${{ env.LATEST_AMI }}" \
-      .
+          JAR_FILE=$(find ./backend-jar -name "*.jar" -type f)
+          if [ -z "$JAR_FILE" ]; then
+            echo "Error: No JAR file found"
+            exit 1
+          fi
+          echo "Using JAR file: $JAR_FILE"
+          packer build \
+            -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
+            -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
+            -var "COMPILED_JAR_PATH=$JAR_FILE" \
+            -var "source_ami=${{ env.LATEST_AMI }}" \
+            .
       
       - name: Check backend-jar content after Packer
         run: |
